--- 
- name: sub-element access styles 
  hosts: localhost 
  gather_facts: false 
  vars: 
    - derp: 
        keys: 
          - c 
          - d 
  tasks: 
    - name: subscript style 
      debug: 
        var: derp['keys']  
    - name: dot notation style 
      debug: 
        var: derp.keys 

