--- 
- name: test remote_copy module 
  hosts: localhost 
  gather_facts: false 
 
  tasks: 
  - name: ensure foo 
    file: 
      path: /tmp/rcfoo 
      state: touch 
 
  - name: do a remote copy 
    remote_copy: 
      source: /tmp/rcfoo 
      dest: /tmp/rcbar 

  - name: show a fact 
    debug: 
      var: rc_dest 
