---
- name: vars
  hosts: localhost
  gather_facts: true

  tasks:
  - name: load variables
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}.yaml"
      - "{{ ansible_os_family }}.yaml"
      - variables.yaml

  - name: a task
    debug:
      msg: "I am a {{ varname }}"
