--- 
- name: touch files 
  hosts: localhost 
  gather_facts: false 
 
  tasks: 
  - name: a task 
    debug: 
      msg: "I am a changing task" 
    changed_when: true 
    notify: a handler 
 
  handlers: 
  - include: handlers.yaml 
    when: foo | default('true') | bool 
