---
- name: touch files
  hosts: localhost
  gather_facts: false

  tasks:
  - include: files.yaml
    vars:
      files:
        herp:
          path: /tmp/foo
        derp:
          path: /tmp/foo
