--- 
- name: test the inventory 
  hosts: all 
  gather_facts: false 
 
  tasks: 
  - name: hello world 
    debug: 
      msg: "Hello world, I am {{ inventory_hostname }}. 
            My username is {{ ansible_ssh_user }}"
