--- 
- name: error handling 
  hosts: localhost
  gather_facts: false 
 
  tasks: 
  - name: delete branch bad
    command: git branch -D badfeature
    args:
      chdir: /srv/app
    register: gitout
    failed_when:
      - gitout.rc != 0
      - not gitout.stderr is search('branch.*not found')
